name: "SnapTrap"
version: "2.1.0"
slug: "snaptrap"
description: "Application de détection de claquement de doigts en temps réel utilisant YAMNet, compatible avec les flux audio locaux et RTSP"
url: "https://github.com/Yoyobot12/Snaptrap"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
host_network: true
#ports:
#  "16045/tcp": 16045
#  "6980/tcp": 6980
init: false
webui: "http://[HOST]:[PORT:16045]"
maintainer: "Yoyobot12"
